### ISSUE TITLE
Objects placed close together don't get spawned at correct location

### ISSUE THREAD

**Issue by astruyk** [SilentSpike/ARMA-SilentMapConverter#10]
It looks like objects get shifted to avoid collisions - this messes up things like sandbags. Consider using "CAN_COLLIDE" instead of "FORM" for those objects to allow them to be placed in the same spot as originally pulled from.

To repro:
1) Create a mission with two overlapping sandbags (that is, with their ends touching and overlapping slightly so they appear to be one object).
2) Run script on mission
3) Run generated SQF code to re-create original objects. They appear in different locations than originally placed.

**Comment by SilentSpike** [comment]
Sorry it's taken me a while to get around to these issues, I appreciate the detailed and thoughtful reports :smile:

It's weird that this happens since the editor also uses `FORM` by default (which was my reasoning for doing so). Since they end up in different positions than expected I changed it to use `CAN_COLLIDE` and did some testing, turns out they still get moved apart for some reason.

Will try and find a workaround for this.

**Comment by SilentSpike** [comment]
Objects now use `CAN_COLLIDE` by default. This is the best I can do as no variation of setPos/createVehicle seems to remove the object misplacement. `CAN_COLLIDE` works sometimes, but not always.

**Comment by astruyk** [comment]
`CAN_COLLIDE` worked in all the cases I had. It was part of the submitted patch.

**Comment by astruyk** [comment]
Looked at your fix ( 6b8c521480a3a50bec0900d2ca48c75434fe976d ) and it looks like you only updated one of the two places you were setting "FORM". In the patch I changed it in both places.

**Comment by SilentSpike** [comment]
Yeah, that was intentional. Since the editor defaults to FORM and I'd rather not remove the ability to use the setting since it might be desirable. (It's fine for objects since it doesn't actually match editor behaviour).
